/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author darcy
 */
public class FrmOficial extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmOficial
     */
    public FrmOficial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblLucernafoto = new javax.swing.JLabel();
        lblZurichfoto = new javax.swing.JLabel();
        lblGinebrafoto = new javax.swing.JLabel();
        lblBasileafoto = new javax.swing.JLabel();
        lblBernafoto = new javax.swing.JLabel();
        lblBernaNombre = new javax.swing.JLabel();
        lblZurichNombre = new javax.swing.JLabel();
        lblLucernaNombre = new javax.swing.JLabel();
        lblGinebraNombre = new javax.swing.JLabel();
        lblBasileaNombre = new javax.swing.JLabel();
        lblTren = new javax.swing.JLabel();
        lblTren1 = new javax.swing.JLabel();
        lblTren2 = new javax.swing.JLabel();
        lblTren3 = new javax.swing.JLabel();
        lblTren4 = new javax.swing.JLabel();
        lblTren5 = new javax.swing.JLabel();
        lblCantidadPersxFila = new javax.swing.JLabel();
        lblPersxTren = new javax.swing.JLabel();
        lblPersxTren1 = new javax.swing.JLabel();
        lblPersxTren2 = new javax.swing.JLabel();
        lblPersxTren3 = new javax.swing.JLabel();
        lblPersxTren4 = new javax.swing.JLabel();
        lblPersxTren5 = new javax.swing.JLabel();
        lblCantidadTrenes1 = new javax.swing.JLabel();
        lblCantidadPersxTren1 = new javax.swing.JLabel();
        lblQueue = new javax.swing.JLabel();
        lblQueue1 = new javax.swing.JLabel();
        lblQueue2 = new javax.swing.JLabel();
        lblQueue3 = new javax.swing.JLabel();
        lblQueue4 = new javax.swing.JLabel();
        lblQueue5 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLucernafoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Lucerna.jpg"))); // NOI18N
        lblLucernafoto.setText("jLabel2");
        jDesktopPane1.add(lblLucernafoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 160, 100));

        lblZurichfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/zurich.jpg"))); // NOI18N
        lblZurichfoto.setText("jLabel2");
        jDesktopPane1.add(lblZurichfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 100));

        lblGinebrafoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/ginebra.jpg"))); // NOI18N
        lblGinebrafoto.setText("jLabel2");
        jDesktopPane1.add(lblGinebrafoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, 100));

        lblBasileafoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Basilea.jpg"))); // NOI18N
        lblBasileafoto.setText("jLabel2");
        jDesktopPane1.add(lblBasileafoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, 100));

        lblBernafoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Berna.jpg"))); // NOI18N
        lblBernafoto.setText("jLabel2");
        jDesktopPane1.add(lblBernafoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 150, 100));

        lblBernaNombre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblBernaNombre.setText("Berna");
        jDesktopPane1.add(lblBernaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 50, 20));

        lblZurichNombre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblZurichNombre.setText("Zurich");
        jDesktopPane1.add(lblZurichNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 60, 20));

        lblLucernaNombre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblLucernaNombre.setText("Lucerna");
        jDesktopPane1.add(lblLucernaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 80, 20));

        lblGinebraNombre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblGinebraNombre.setText("Ginebra");
        jDesktopPane1.add(lblGinebraNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 70, 20));

        lblBasileaNombre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblBasileaNombre.setText("Basilea");
        jDesktopPane1.add(lblBasileaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 70, 20));

        lblTren.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/tren 2.jpg"))); // NOI18N
        jDesktopPane1.add(lblTren, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 30));

        lblTren1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/tren 2.jpg"))); // NOI18N
        jDesktopPane1.add(lblTren1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 50, 30));

        lblTren2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/tren 2.jpg"))); // NOI18N
        jDesktopPane1.add(lblTren2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 50, 30));

        lblTren3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/tren 2.jpg"))); // NOI18N
        jDesktopPane1.add(lblTren3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 50, 30));

        lblTren4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/tren 2.jpg"))); // NOI18N
        jDesktopPane1.add(lblTren4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 50, 30));

        lblTren5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/tren 2.jpg"))); // NOI18N
        jDesktopPane1.add(lblTren5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 50, 30));

        lblCantidadPersxFila.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblCantidadPersxFila.setText("Cantidad de personas en fila por ciudad");
        jDesktopPane1.add(lblCantidadPersxFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        lblPersxTren.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/person2.jpg"))); // NOI18N
        jDesktopPane1.add(lblPersxTren, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 40, 20));

        lblPersxTren1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/person2.jpg"))); // NOI18N
        jDesktopPane1.add(lblPersxTren1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 40, 20));

        lblPersxTren2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/person2.jpg"))); // NOI18N
        jDesktopPane1.add(lblPersxTren2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 40, 20));

        lblPersxTren3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/person2.jpg"))); // NOI18N
        jDesktopPane1.add(lblPersxTren3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 40, 20));

        lblPersxTren4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/person2.jpg"))); // NOI18N
        jDesktopPane1.add(lblPersxTren4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 40, 20));

        lblPersxTren5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/person2.jpg"))); // NOI18N
        jDesktopPane1.add(lblPersxTren5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 40, 20));

        lblCantidadTrenes1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblCantidadTrenes1.setText("Cantidad de trenes en la Ciudad");
        jDesktopPane1.add(lblCantidadTrenes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, 30));

        lblCantidadPersxTren1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblCantidadPersxTren1.setText("Cantidad de personas por Tren");
        jDesktopPane1.add(lblCantidadPersxTren1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        lblQueue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/queue.jpg"))); // NOI18N
        jDesktopPane1.add(lblQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, 30));

        lblQueue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/queue.jpg"))); // NOI18N
        jDesktopPane1.add(lblQueue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        lblQueue2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/queue.jpg"))); // NOI18N
        jDesktopPane1.add(lblQueue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 68, -1, 30));

        lblQueue3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/queue.jpg"))); // NOI18N
        jDesktopPane1.add(lblQueue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, 30));

        lblQueue4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/queue.jpg"))); // NOI18N
        jDesktopPane1.add(lblQueue4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 30));

        lblQueue5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/queue.jpg"))); // NOI18N
        jDesktopPane1.add(lblQueue5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo.jpg"))); // NOI18N
        lblFondo.setText("jLabel1");
        jDesktopPane1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 690, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel lblBasileaNombre;
    private javax.swing.JLabel lblBasileafoto;
    private javax.swing.JLabel lblBernaNombre;
    private javax.swing.JLabel lblBernafoto;
    private javax.swing.JLabel lblCantidadPersxFila;
    private javax.swing.JLabel lblCantidadPersxTren1;
    private javax.swing.JLabel lblCantidadTrenes1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGinebraNombre;
    private javax.swing.JLabel lblGinebrafoto;
    private javax.swing.JLabel lblLucernaNombre;
    private javax.swing.JLabel lblLucernafoto;
    private javax.swing.JLabel lblPersxTren;
    private javax.swing.JLabel lblPersxTren1;
    private javax.swing.JLabel lblPersxTren2;
    private javax.swing.JLabel lblPersxTren3;
    private javax.swing.JLabel lblPersxTren4;
    private javax.swing.JLabel lblPersxTren5;
    private javax.swing.JLabel lblQueue;
    private javax.swing.JLabel lblQueue1;
    private javax.swing.JLabel lblQueue2;
    private javax.swing.JLabel lblQueue3;
    private javax.swing.JLabel lblQueue4;
    private javax.swing.JLabel lblQueue5;
    private javax.swing.JLabel lblTren;
    private javax.swing.JLabel lblTren1;
    private javax.swing.JLabel lblTren2;
    private javax.swing.JLabel lblTren3;
    private javax.swing.JLabel lblTren4;
    private javax.swing.JLabel lblTren5;
    private javax.swing.JLabel lblZurichNombre;
    private javax.swing.JLabel lblZurichfoto;
    // End of variables declaration//GEN-END:variables
}
