/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author darcy
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPanel = new javax.swing.JDesktopPane();
        lblIntro1 = new javax.swing.JLabel();
        lblIntroSombra = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(dskPanel);
        dskPanel.setBounds(43, 437, 737, 412);

        lblIntro1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        lblIntro1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 42)); // NOI18N
        lblIntro1.setForeground(new java.awt.Color(0, 0, 102));
        lblIntro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIntro1.setText("Bienvenido al sistema de Trenes");
        getContentPane().add(lblIntro1);
        lblIntro1.setBounds(60, 110, 630, 100);

        lblIntroSombra.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        lblIntroSombra.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 42)); // NOI18N
        lblIntroSombra.setForeground(new java.awt.Color(245, 203, 168));
        lblIntroSombra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIntroSombra.setText("Bienvenido al sistema de Trenes");
        getContentPane().add(lblIntroSombra);
        lblIntroSombra.setBounds(60, 110, 620, 100);

        jButton1.setBackground(new java.awt.Color(242, 208, 174));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 25)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 51));
        jButton1.setText("Continuar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 102), new java.awt.Color(0, 0, 102), new java.awt.Color(0, 0, 102), new java.awt.Color(0, 0, 102)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 380, 140, 30);

        lblFondo.setBackground(new java.awt.Color(246, 242, 238));
        lblFondo.setForeground(new java.awt.Color(255, 153, 51));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/suiza.jpg"))); // NOI18N
        lblFondo.setText("jLabel1");
        getContentPane().add(lblFondo);
        lblFondo.setBounds(-20, 0, 730, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    FrmOficial vOficial = new FrmOficial();
        dskPanel.add(vOficial);
        vOficial.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIntro1;
    private javax.swing.JLabel lblIntroSombra;
    // End of variables declaration//GEN-END:variables
}
