/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Ventanas;

import java.util.Random;
import classes.FilaPasajeros;

/**
 *
 * @author darcy
 */
public class FrmOficial extends javax.swing.JInternalFrame {

    FilaPasajeros zurich;
    FilaPasajeros basilea;
    FilaPasajeros ginebra;
    FilaPasajeros berna;
    FilaPasajeros lucerna;
    Random rn;
    /**
     * Creates new form FrmOficial
     */
    public FrmOficial() {
        initComponents();
        zurich = new FilaPasajeros();
        basilea = new FilaPasajeros();
        ginebra = new FilaPasajeros();
        berna = new FilaPasajeros();
        lucerna = new FilaPasajeros();
        rn = new Random();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblPasajeros = new javax.swing.JLabel();
        lblTren = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblPasajerosT2 = new javax.swing.JLabel();
        lblCiudadT10 = new javax.swing.JLabel();
        lblCiudadT2 = new javax.swing.JLabel();
        lblCiudadT3 = new javax.swing.JLabel();
        lblCiudadT4 = new javax.swing.JLabel();
        lblCiudadT5 = new javax.swing.JLabel();
        lblCiudadT6 = new javax.swing.JLabel();
        lblCiudadT7 = new javax.swing.JLabel();
        lblCiudadT8 = new javax.swing.JLabel();
        lblCiudadT9 = new javax.swing.JLabel();
        lblCiudadT1 = new javax.swing.JLabel();
        lblPasajerosT1 = new javax.swing.JLabel();
        lblPasajerosT3 = new javax.swing.JLabel();
        lblPasajerosT4 = new javax.swing.JLabel();
        lblPasajerosT5 = new javax.swing.JLabel();
        lblPasajerosT6 = new javax.swing.JLabel();
        lblPasajerosT7 = new javax.swing.JLabel();
        lblPasajerosT8 = new javax.swing.JLabel();
        lblPasajerosT9 = new javax.swing.JLabel();
        lblPasajerosT10 = new javax.swing.JLabel();
        lblPasajerosFondo = new javax.swing.JLabel();
        lblTren1 = new javax.swing.JLabel();
        lblTren2 = new javax.swing.JLabel();
        lblTren3 = new javax.swing.JLabel();
        lblTren4 = new javax.swing.JLabel();
        lblTren5 = new javax.swing.JLabel();
        lblTren6 = new javax.swing.JLabel();
        lblTren7 = new javax.swing.JLabel();
        lblTren8 = new javax.swing.JLabel();
        lblTren9 = new javax.swing.JLabel();
        lblTren10 = new javax.swing.JLabel();
        lblTrenFondo = new javax.swing.JLabel();
        lblCiudadFondo = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblFilaLucerna = new javax.swing.JLabel();
        lblFilaBerna = new javax.swing.JLabel();
        lblFilaGinebra = new javax.swing.JLabel();
        lblFilaBasilea = new javax.swing.JLabel();
        lblFilaZurich = new javax.swing.JLabel();
        lblFilaBasileaPersona = new javax.swing.JLabel();
        lblFilaLucernaPersona = new javax.swing.JLabel();
        lblFilaBernaPersona = new javax.swing.JLabel();
        lblFilaGinebraPersona = new javax.swing.JLabel();
        lblFilaZurichPersona = new javax.swing.JLabel();
        lblFondoFila = new javax.swing.JLabel();
        lbltodos = new javax.swing.JLabel();
        btnViajar = new java.awt.Button();
        lblFondo = new javax.swing.JLabel();

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPasajeros.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        lblPasajeros.setText("Pasajeros");
        jDesktopPane1.add(lblPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        lblTren.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        lblTren.setText("Tren");
        jDesktopPane1.add(lblTren, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblCiudad.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        lblCiudad.setText("Ciudad");
        jDesktopPane1.add(lblCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel1.setText("Personas en Fila");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 150, 30));

        lblTitulo.setBackground(new java.awt.Color(255, 235, 204));
        lblTitulo.setForeground(new java.awt.Color(255, 235, 204));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/blue.png"))); // NOI18N
        lblTitulo.setText("lblFondoFila");
        jDesktopPane1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 170, 30));

        lblPasajerosT2.setText("_________");
        jDesktopPane1.add(lblPasajerosT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 50, 30));

        lblCiudadT10.setText("_________");
        jDesktopPane1.add(lblCiudadT10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        lblCiudadT2.setText("_________");
        jDesktopPane1.add(lblCiudadT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        lblCiudadT3.setText("_________");
        jDesktopPane1.add(lblCiudadT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        lblCiudadT4.setText("_________");
        jDesktopPane1.add(lblCiudadT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        lblCiudadT5.setText("_________");
        jDesktopPane1.add(lblCiudadT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        lblCiudadT6.setText("_________");
        jDesktopPane1.add(lblCiudadT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        lblCiudadT7.setText("_________");
        jDesktopPane1.add(lblCiudadT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        lblCiudadT8.setText("_________");
        jDesktopPane1.add(lblCiudadT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        lblCiudadT9.setText("_________");
        jDesktopPane1.add(lblCiudadT9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        lblCiudadT1.setText("_________");
        jDesktopPane1.add(lblCiudadT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 50, 30));

        lblPasajerosT1.setText("_________");
        jDesktopPane1.add(lblPasajerosT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 50, 30));

        lblPasajerosT3.setText("_________");
        jDesktopPane1.add(lblPasajerosT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 50, 20));

        lblPasajerosT4.setText("_________");
        jDesktopPane1.add(lblPasajerosT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 50, 20));

        lblPasajerosT5.setText("_________");
        jDesktopPane1.add(lblPasajerosT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 50, 20));

        lblPasajerosT6.setText("_________");
        jDesktopPane1.add(lblPasajerosT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 50, 20));

        lblPasajerosT7.setText("_________");
        jDesktopPane1.add(lblPasajerosT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 50, 20));

        lblPasajerosT8.setText("_________");
        jDesktopPane1.add(lblPasajerosT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 50, 20));

        lblPasajerosT9.setText("_________");
        jDesktopPane1.add(lblPasajerosT9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 50, 20));

        lblPasajerosT10.setText("_________");
        jDesktopPane1.add(lblPasajerosT10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 50, 20));

        lblPasajerosFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/vertical1.png"))); // NOI18N
        jDesktopPane1.add(lblPasajerosFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 80, 300));

        lblTren1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTren1.setText("10");
        jDesktopPane1.add(lblTren1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 20, -1));

        lblTren2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTren2.setText("1");
        jDesktopPane1.add(lblTren2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 20, -1));

        lblTren3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTren3.setText("2");
        jDesktopPane1.add(lblTren3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 20, -1));

        lblTren4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTren4.setText("3");
        jDesktopPane1.add(lblTren4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 20, -1));

        lblTren5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTren5.setText("4");
        jDesktopPane1.add(lblTren5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 20, -1));

        lblTren6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTren6.setText("5");
        jDesktopPane1.add(lblTren6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 20, -1));

        lblTren7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTren7.setText("6");
        jDesktopPane1.add(lblTren7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 20, -1));

        lblTren8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTren8.setText("7");
        jDesktopPane1.add(lblTren8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 20, -1));

        lblTren9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTren9.setText("8");
        jDesktopPane1.add(lblTren9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 20, -1));

        lblTren10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTren10.setText("9");
        jDesktopPane1.add(lblTren10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 20, -1));

        lblTrenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/verticalita.png"))); // NOI18N
        jDesktopPane1.add(lblTrenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 300));

        lblCiudadFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Vertical.png"))); // NOI18N
        jDesktopPane1.add(lblCiudadFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 80, 300));

        lblTitulo1.setBackground(new java.awt.Color(255, 235, 204));
        lblTitulo1.setForeground(new java.awt.Color(255, 235, 204));
        lblTitulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/wallpaper (1).png"))); // NOI18N
        lblTitulo1.setText("jLabel1");
        jDesktopPane1.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 310, 30));

        lblFilaLucerna.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblFilaLucerna.setText("Lucerna:");
        jDesktopPane1.add(lblFilaLucerna, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        lblFilaBerna.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblFilaBerna.setText("Berna:");
        jDesktopPane1.add(lblFilaBerna, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        lblFilaGinebra.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblFilaGinebra.setText("Ginebra:");
        jDesktopPane1.add(lblFilaGinebra, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        lblFilaBasilea.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblFilaBasilea.setText("Basilea:");
        jDesktopPane1.add(lblFilaBasilea, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        lblFilaZurich.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblFilaZurich.setText("Zurich:");
        jDesktopPane1.add(lblFilaZurich, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        lblFilaBasileaPersona.setText("___________");
        jDesktopPane1.add(lblFilaBasileaPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        lblFilaLucernaPersona.setText("___________");
        jDesktopPane1.add(lblFilaLucernaPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        lblFilaBernaPersona.setText("___________");
        jDesktopPane1.add(lblFilaBernaPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        lblFilaGinebraPersona.setText("___________");
        jDesktopPane1.add(lblFilaGinebraPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        lblFilaZurichPersona.setText("___________");
        jDesktopPane1.add(lblFilaZurichPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        lblFondoFila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/blue.png"))); // NOI18N
        lblFondoFila.setText("jLabel2");
        jDesktopPane1.add(lblFondoFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 170, 230));

        lbltodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/todos.png"))); // NOI18N
        jDesktopPane1.add(lbltodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 90, 340));

        btnViajar.setLabel("Viajar");
        btnViajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnViajar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo.jpg"))); // NOI18N
        lblFondo.setText("jLabel1");
        jDesktopPane1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 700, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajarActionPerformed
        // TODO add your handling code here:
        int num = rn.nextInt(5) + 1;
        //llega un tren a la ciuidad, se deben agregar 15 pasajeros a la lista de espera
        zurich.agregarNuevosPasajeros();
        System.out.println(zurich.devolverPasajeros());
        System.out.println("**************************************");
        System.out.println("Se eliminaran los pasajeros de la cuidad: " + num);
        //cuando el tren se va, se lleva todos los pasajeros de la cuidad destino (num)
        int pasajerosViajando = zurich.retirarPasajerosPorCiudad(num);
        // pasajerosViajando es lo que debe ir en la propiedad del tren
        System.out.println("Estan " + pasajerosViajando +  " pasajeros viajando a la cuidad " + num);
        //como control, la lista ahora no tiene los pasajeros que ya estan viajando
        System.out.println(zurich.devolverPasajeros());
        System.out.println("***************FINAL*******************");
        
    }//GEN-LAST:event_btnViajarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnViajar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCiudadFondo;
    private javax.swing.JLabel lblCiudadT1;
    private javax.swing.JLabel lblCiudadT10;
    private javax.swing.JLabel lblCiudadT2;
    private javax.swing.JLabel lblCiudadT3;
    private javax.swing.JLabel lblCiudadT4;
    private javax.swing.JLabel lblCiudadT5;
    private javax.swing.JLabel lblCiudadT6;
    private javax.swing.JLabel lblCiudadT7;
    private javax.swing.JLabel lblCiudadT8;
    private javax.swing.JLabel lblCiudadT9;
    private javax.swing.JLabel lblFilaBasilea;
    private javax.swing.JLabel lblFilaBasileaPersona;
    private javax.swing.JLabel lblFilaBerna;
    private javax.swing.JLabel lblFilaBernaPersona;
    private javax.swing.JLabel lblFilaGinebra;
    private javax.swing.JLabel lblFilaGinebraPersona;
    private javax.swing.JLabel lblFilaLucerna;
    private javax.swing.JLabel lblFilaLucernaPersona;
    private javax.swing.JLabel lblFilaZurich;
    private javax.swing.JLabel lblFilaZurichPersona;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondoFila;
    private javax.swing.JLabel lblPasajeros;
    private javax.swing.JLabel lblPasajerosFondo;
    private javax.swing.JLabel lblPasajerosT1;
    private javax.swing.JLabel lblPasajerosT10;
    private javax.swing.JLabel lblPasajerosT2;
    private javax.swing.JLabel lblPasajerosT3;
    private javax.swing.JLabel lblPasajerosT4;
    private javax.swing.JLabel lblPasajerosT5;
    private javax.swing.JLabel lblPasajerosT6;
    private javax.swing.JLabel lblPasajerosT7;
    private javax.swing.JLabel lblPasajerosT8;
    private javax.swing.JLabel lblPasajerosT9;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTren;
    private javax.swing.JLabel lblTren1;
    private javax.swing.JLabel lblTren10;
    private javax.swing.JLabel lblTren2;
    private javax.swing.JLabel lblTren3;
    private javax.swing.JLabel lblTren4;
    private javax.swing.JLabel lblTren5;
    private javax.swing.JLabel lblTren6;
    private javax.swing.JLabel lblTren7;
    private javax.swing.JLabel lblTren8;
    private javax.swing.JLabel lblTren9;
    private javax.swing.JLabel lblTrenFondo;
    private javax.swing.JLabel lbltodos;
    // End of variables declaration//GEN-END:variables
}
